### Numpy ndarray practice

* ndarray 생성 np.array()

In [8]:
import numpy as np

In [9]:
list1 = [1,2,3]

print('list1:',list1)
print('liest1 type:',type(list1))

array1 = np.array(list1)
#list 타입의 list를 ndarray형의 array1으로 변환

print('array1:',array1)
print('array1 type:',type(array1))

list1: [1, 2, 3]
liest1 type: <class 'list'>
array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>


* ndarray의 형태(shape)와 차원

In [10]:
array1 = np.array([1,2,3])

print('array1 type : ',type(array1))
print('array1 array 형태 : ',array1.shape)

array2 = np.array([[1,2,3],[4,5,6]])
print('array2 type',type(array2))
print('array2 array2 형태 :',array2.shape)

array3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('array3 type',type(array3))
print('array3 array 형태 :',array3.shape)

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)
array2 type <class 'numpy.ndarray'>
array2 array2 형태 : (2, 3)
array3 type <class 'numpy.ndarray'>
array3 array 형태 : (3, 3)


In [11]:
list2 = [1,2,'test1']
array2 = np.array(list2)
print(array2,array2.dtype)
#데이터범위가 큰 것으로 형변환이 저절로 이루어진다.
#int -> float int -> string 등등

['1' '2' 'test1'] <U11


* astype()을 통한 타입 변환

In [12]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float,array_float.dtype)


array_float2 = np.array([1.,2.,3.])
array_int2 = array_float2.astype('int64')

print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int64


* ndarray에서 axis 기반의 연산함수 수행

In [13]:
array2 = np.array([[1,2,3],[4,5,6]])
                   
print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

21
[5 7 9]
[ 6 15]


* ndarray를 편하게 생성하기 - arrange, zeros, ones

In [14]:
arr1 = np.arange(10)
print(arr1)

n,m = map(int, input().split())
arr2 = arr1.reshape(-1,m)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
2 10
[[0 1 2 3 4 5 6 7 8 9]]


In [15]:
sequence_array = np.arange(10)
print(sequence_array)
#행렬의 자료형과, 배열 형태
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [16]:
#0으로 초기화된 3행 2열의 2차원 배열
zero_arr = np.zeros((3,2),dtype='int32')
print(zero_arr)
print(zero_arr.dtype, zero_arr.shape)

#1로 초기화된 3행 2열의 2차원 배열
one_arr = np.ones((3,2),dtype='int32')
print(one_arr)
print(one_arr.dtype,one_arr.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1 1]
 [1 1]
 [1 1]]
int32 (3, 2)


* ndarray의 shape를 변경하는 reshape()

    1) reshape()에 -1인 인자값을 부여하여 특정 차원으로 고정된 가변적인 ndarray형태 변환도 가능하다.

In [17]:
arr1 = np.arange(10)

arr2 = arr1.reshape((2,5))
print(arr2)
arr3 = arr2.reshape(-1,1)
print(arr3)
#변환할 수 없는 shape구조를 입력하면 오류가 발생한다.

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [18]:
arr1 = np.arange(10)
#컬럼 axis는 고정을 5로 만들고, 행은 그에 맞춰서..
arr2 = arr1.reshape(-1,5)
print('arr2 shape : ',arr2.shape)
print('arr2 : \n',arr2)


#로우 axis는 5로 고정하고 컬럼 axis 크기는 이에 맞춰 자동적으로 변환. 즉 5x2로 
arr3 = arr1.reshape(5,-1)
print('arr3 shape : ',arr3.shape)
print('arr3 : \n',arr3)

arr2 shape :  (2, 5)
arr2 : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr3 shape :  (5, 2)
arr3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [19]:
#reshape()는 (-1,1), (-1,)와 같은 형태로 주로 사용됨
#1차원 ndarray를 2차원으로 또는 2차원 ndarray를 1차원으로 변환 시 사용
arr1 = np.arange(5)

#1차원 ndarray를 2차원으로 변환하되, 컬럼axis크기는 반드시 1이어야 한다.
arr2d_1 = arr1.reshape(-1,1)
print('arr2d_1 shape :',arr2d_1.shape)
print('arr2d_1 : \n',arr2d_1)

#2차원 ndarray를 1차원으로 변환
arr1d = arr2d_1.reshape(-1,)
print('arr1d shape :',arr1d.shape)
print('arr1d : \n',arr1d)

arr2d_1 shape : (5, 1)
arr2d_1 : 
 [[0]
 [1]
 [2]
 [3]
 [4]]
arr1d shape : (5,)
arr1d : 
 [0 1 2 3 4]


In [20]:
#-1을 적용하여도 변환이 불가능한 형태로의 변환을 요구할 경우 오류가 발생한다.
array1 = np.arange(10)
arr4 = arr1.reshape(-1,5)

#그리고 reshape에서 -1 인자값은 하나만 들어갈 수 있다. 

#### 인덱싱

In [21]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [22]:
#뭔가 상당히 c스러운 코딩..ㅋㅋ
print(arr2d.shape)

#행과 열 번호를 얻기 위해선 shape[1], shape[0]을 하면 된다..
#이를 통해 합을 2중 포문을 통해 구할 수 있음. 

print('arr2d의 열의 크기 : ',arr2d.shape[1])
print('arr2d의 행의 크기 : ',arr2d.shape[0])
total=0
for i in range(arr2d.shape[1]):
    for j in range(arr2d.shape[0]):
       total+=arr2d[i][j]

print(total)

(3, 3)
arr2d의 열의 크기 :  3
arr2d의 행의 크기 :  3
45


In [23]:
#Pythonic한 코딩은 슬라이싱을 통해 할 수 있다.

total1 = arr2d[::].sum()
print(total1)

45


1) 팬시 인덱싱(Fancy indexing)은 배열에 인덱스 번호를 지정하면 그 인덱스에 알맞는 value를 리턴하는 방식인다. 해쉬, 맵과 비슷하다.

In [36]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1],2]
print('array2d[[0,1],2] => ',array3.tolist())

array4 = array2d[[0,2],0:2]
print('array2d[[0,2],0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1],2] =>  [3, 6]
array2d[[0,2],0:2] =>  [[1, 2], [7, 8]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


2) 불린 인덱싱(Boolean indexing)은 조건 필터링 & 검색을 동시에 할 수 있기 때문에 매우 자주 사용된다.
      
  * 만일 ndarray 내의 값이 5보다 큰 ndarray요소들을 추출 하고자 한다면?

In [28]:
#불린 인덱싱을 사용하지 않은 경우

array1d = np.arange(start=1,stop=10)
target=[]

for i in range(0,9):
    if array1d[i]>5:
        target.append(array1d[i])

array_selected = np.array(target)
print(array_selected)

[6 7 8 9]


In [29]:
#불린 인덱싱을 사용한 경우
print(array1d[array1d>5])

[6 7 8 9]


In [38]:
boolean_indexes = np.array([False,False,False,False,False,True,True,True,True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :',array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [39]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
#5,6,7,8 인덱스에 해당하는 데이터값이 출력됨.
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 - sort()와 argsort()

####   1) 행렬 정렬

In [43]:
org_array = np.array([3,1,9,5])
print('원본 행렬 : ',org_array)

#np.sort()로 오름차순 정렬
sort_array1 = np.sort(org_array)

print('np.sort() 호출 후 반환된 행렬 :',sort_array1)
print('np.sort() 호출 후 원본 행렬 :',org_array)

#np.sort()로 내림차순 정렬
sort_desc_array1 = np.sort(org_array)[::-1]

print('np.sort() 호출 후 반환된 행렬 :',sort_desc_array1)
print('np.sort() 호출 후 원본 행렬 :',org_array)

#.ndarray.sort()로 정렬 이 결과도 같을까?

sort_array2 = org_array.sort()

org_array.sort()

print('org_array.sort() 호출 후 반환된 행렬 :',sort_array2)
print('org_array.sort() 호출 후 원본 행렬 :',org_array)

# ndarray.sort()[::-1]로 내림차순 정렬

sort_desc_array2 = org_array.sort()[::-1]
org_array.sort()[::-1]

#rint('org_array.sort()[::-1] 호출 후 반환된 행렬 :',sort_desc_array2)
#print('org_array.sort()[::-1] 호출 후 원본 행렬 : ',org_array)


원본 행렬 :  [3 1 9 5]
np.sort() 호출 후 반환된 행렬 : [1 3 5 9]
np.sort() 호출 후 원본 행렬 : [3 1 9 5]
np.sort() 호출 후 반환된 행렬 : [9 5 3 1]
np.sort() 호출 후 원본 행렬 : [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬 : None
org_array.sort() 호출 후 원본 행렬 : [1 3 5 9]


TypeError: 'NoneType' object is not subscriptable

<결론>

arr1.sort()는 원본 자체에다가 덮어씌우는 결과를 가져오고
np.sort(arr1)은 원본행렬은 유지한 채, arr1의 정렬 결과를 따로 저장함을 알 수 있다.

In [44]:
#2차원 행렬에서의 정렬

array2d = np.array([[8,12],[7,1]])

sort_array2d_axis0 = np.sort(array2d,axis=0)
print('로우 방향으로 정렬 : \n',sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d,axis=1)
print('컬럼 방향으로 정렬 : \n',sort_array2d_axis1)

로우 방향으로 정렬 : 
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


In [47]:
# 2차원 행렬 좀 더 자세히..

# 1) 좌에서 우로 정렬 : 컬럼 기준 정렬
x2 = np.array([[1,2,6],[0,4,7],[2,3,5]])

x2_axis1 = np.sort(x2,axis=1)
print(x2_axis1,'\n')

# 2) 위에서 아래로 정렬 : 로우 기준 정렬
x2_axis0 = np.sort(x2,axis=0)
print(x2_axis0)

[[1 2 6]
 [0 4 7]
 [2 3 5]] 

[[0 2 5]
 [1 3 6]
 [2 4 7]]


####    2) argsort

In [49]:
org_array = np.array([3,1,9,5])
print(np.sort(org_array))

sort_indices = np.argsort(org_array)

print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 : ',sort_indices)

[1 3 5 9]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 :  [1 0 3 2]


In [50]:
#이를 내림차순으로 정렬할 수 있다.

sort_indices_desc = np.argsort(org_array)[::-1]

print(type(sort_indices_desc))
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스 :',sort_indices_desc)

<class 'numpy.ndarray'>
행렬 내림차순 정렬 시 원본 행렬의 인덱스 : [2 3 0 1]


* key -value 형태의 데이터를 John=78, Mike=95, Sarah = 84, Kate =98, Samuel=88을 ndarray로 만들고, argsort()를 이용하여 key에 해당하는 값들을 정렬



* 사람을 출력 사람이 key이기 때문

In [51]:
name = np.array(['John','Mike','Sarah','Kate','Samuel'])

score = np.array([78,95,84,98,88])

#score_array의 정렬된 값에 해당하는 원본 행렬의, 위치 인덱스를 반환
sort_indices = np.argsort(score)

print('sort_indices : ',sort_indices)

name_array_sort = name[sort_indices]

score_array_sort = score[sort_indices]

print(name_array_sort)
print(score_array_sort)

sort_indices :  [0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
[78 84 88 95 98]


#### 선형대수 연산 - 행렬 내적과 전치행렬 구하기


##### 1) 행렬 내적

In [53]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])

dot_product = np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]


#### 2) 전치 행렬

In [56]:
A =np.array([[1,2],[3,4]])

transpose_mat = np.transpose(A)

print('A의 전치 행렬 : \n',transpose_mat)

A의 전치 행렬 : 
 [[1 3]
 [2 4]]
