#### Reshape함수

- 차원을 변경할 때 많이 쓰입니다.
- 2차원을 1차원으로, 1차원을 2차원으로 변경할 때 쓰입니다.

In [24]:
import numpy as np
import pandas as pd


sequence_array = np.arange(10)

In [25]:
print(sequence_array)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)

print()
one_array = np.ones((3,2))
print(one_array)

[[0 0]
 [0 0]
 [0 0]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [35]:
array1d = np.arange(10)
print(array1d)


array2d = array1d.reshape(2,5)

print(array2d)

print()

array3d = array1d.reshape(5,2)

print(array3d)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#### reshape(-1,5) 를 하면 -1을 제외한 다른 축이 고정이 되면서 가변적으로 설정이 됩니다.

In [36]:
array1d = np.arange(10)

print(array1d)

array2d  = array1d.reshape(2,5)

print('array2d :',array2d)


# 로우 axis 크기는 5로 고정하고 컬럼 axis 크기는 이에 맞춰서 자동으로 변환합니다. 
array3d = array1d.reshape(5,-1)

print('array3d',array3d)

[0 1 2 3 4 5 6 7 8 9]
array2d : [[0 1 2 3 4]
 [5 6 7 8 9]]
array3d [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


#### reshape(-1,1)은 2차원 1행 x열로 변환하게 하는 것이고, 
#### reshape(-1,)은 1차원 배열로 flatten하게 만드는 방법이다.

In [38]:
array1d = np.arange(10)

array4d = array1d.reshape(-1,1)

print('4d:',array4d)

array5d = array4d.reshape(-1,)

print('5d:',array5d)

4d: [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
5d: [0 1 2 3 4 5 6 7 8 9]


### ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)


- 특정 위치의 단일값을 추출

In [47]:
arr1 = np.arange(9)

arr2 = arr1.reshape(3,3)

print(arr2)
print(arr2[1:3][1:3])
print(arr2[1:3,1:3])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]]
[[4 5]
 [7 8]]


#### 불린 인덱싱 : 매우 자주 사용되는 인덱싱

- ndarray 내의 값이 5보다 큰 array를 추출하고자 한다면???

In [48]:
arr1 = np.arange(1,10)

target = []

for i in range(len(arr1)):
    if arr1[i] >5 :
        target.append(arr1[i])
    else:
        pass
    
array_selected = np.array(target)

print(array_selected)

#이런 식으로 지저분하게 돌려야 하는데 Pythonic한 코드는

[6 7 8 9]


In [55]:
arr2d = [[8,12],
        [7,1]]

arr2d0=np.sort(arr2d,axis=0)
arr2d1 = np.sort(arr2d,axis=1)

print(arr2d0)
print(arr2d1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


#### 행렬의 정렬 - sort()와 argsort()
- 행렬 정렬

In [63]:
org_array = np.array([3,1,9,5])

print('원본 행렬 :',org_array)

#np.sort()로 정렬합니다.
#org_array를 인자로 call_by_ref로 넘겨주는 방식
sort_array1 = np.sort(org_array)

#ndarray.sort()로 정렬
#원본 행렬에 그 자체에 대해 정렬을 해두는 것입니다.
sort_array2 = org_array.sort()

print(sort_array2)
print(org_array)

원본 행렬 : [3 1 9 5]
None
[1 3 5 9]
