 ### 데이터 인코딩
 
 - 레이블 인코딩(Label encoding)

In [3]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']


#LabelEncoder를 객체로 생성한 뒤 fit()과 transform()으로 label 인코딩을 합니다.

encoder= LabelEncoder()
#생성된 인코더 객체에다가 저 item을 학습시킨다.
encoder.fit(items)
labels = encoder.transform(items)

print('인코딩 변환값:',labels)

print('인코딩 클래스:',encoder.classes_)

print('디코딩 원본 값:',encoder.inverse_transform([4,5,2,0,1,1,3,3]))
print('label의 타입:',type(labels))
print('transform을 다시 거꾸로 한 결과:',encoder.inverse_transform(labels))

인코딩 변환값: [0 1 4 5 3 3 2 2]
인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']
디코딩 원본 값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']
label의 타입: <class 'numpy.ndarray'>
transform을 다시 거꾸로 한 결과: ['TV' '냉장고' '전자렌지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


- 원-핫 인코딩(One-Hot encoding)

In [5]:
from sklearn.preprocessing import OneHotEncoder

import numpy as np

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환합니다.
encoder=LabelEncoder()

encoder.fit(items)

labels=encoder.transform(items)

#2차원 데이터로 변환합니다.
#컬럼은 무조건 하나이고, 그에 맞춰 -1은 동적으로 할당을 한다.
labels = labels.reshape(-1,1)


#원 - 핫 인코딩을 적용합니다.

oh_encoder=OneHotEncoder()
oh_encoder.fit(labels)

oh_labels=oh_encoder.transform(labels)

print('원핫 인코딩 데이터')
print(oh_labels.toarray())
print('원핫 인코딩 데이터 차원')
print(oh_labels.shape)

원핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원핫 인코딩 데이터 차원
(8, 6)


In [6]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서'] })
df

item
0    TV
1   냉장고
2  전자렌지
3   컴퓨터
4   선풍기
5   선풍기
6    믹서
7    믹서

In [7]:
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0

### 피처 스케일링 & 정규화

- StandardScaler

In [8]:
from sklearn.datasets import load_iris

import pandas as pd

#붓꽃 데이터 셋을 로딩하고, 이를 DataFrame으로 변환

iris = load_iris()

iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data,columns=iris.feature_names)

print('feature들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [14]:
from sklearn.preprocessing import StandardScaler

#StandardScaler 객체를 만든다.
scaler = StandardScaler()

#StandardScaler로 데이터셋 변환, fit()과 transform() 호출

scaler.fit(iris_df)

iris_scaled = scaler.transform(iris_df)

print('iris_scaled의 타입:',type(iris_scaled))
#transform() 시 scale 변환된 데이터 셋이 numpy ndarray로 변환되어, 
#이를 다시 DataFrame으로 변환

iris_df_scaled = pd.DataFrame(data = iris_scaled,columns=iris.feature_names)

print('feature들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature들의 분산 값')
print(iris_df_scaled.var())

iris_scaled의 타입: <class 'numpy.ndarray'>
feature들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


- MinMaxScaler

In [12]:
from sklearn.preprocessing import MinMaxScaler

#MinMaxScaler 객체 생성
scaler = MinMaxScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('featrue들의 최소 값')
print(iris_df_scaled.min())
print('\nfeature들의 최대 값')
print(iris_df_scaled.max())

featrue들의 최소 값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최대 값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64
