### Python-Numpy vectors

In [12]:
import numpy as np


a = np.random.randn(5)


In [13]:
print(a)

[-1.00684361 -0.92222921  1.94461751  0.59772408  0.2808055 ]


In [14]:
print(a.shape)

(5,)


In [15]:
print(a.T)

[-1.00684361 -0.92222921  1.94461751  0.59772408  0.2808055 ]


In [16]:
print(np.dot(a,a.T))

6.081903835467156


In [17]:
print(a.T)
print("a.T의 shape : ",a.T.shape)
print(a)
print("a의 shape : ",a.shape)

[-1.00684361 -0.92222921  1.94461751  0.59772408  0.2808055 ]
a.T의 shape :  (5,)
[-1.00684361 -0.92222921  1.94461751  0.59772408  0.2808055 ]
a의 shape :  (5,)


##### 위처럼 (5,)의 1차원으로 연산을 하게 되면 T에 대한 인식이 어렵다.

#### 항상 2차원으로 바꿔서 연산을 하도록한다. 

In [18]:
a = np.random.randn(5,1)
print(a.shape)
print("2차원 벡터 a의 shape :",a.shape)

(5, 1)
2차원 벡터 a의 shape : (5, 1)


In [19]:
print(a.T)
print("2차원 벡터 a.T의 shape :",a.T.shape)

[[-1.03914548 -0.36290334 -0.61215103 -0.19500878  1.63246823]]
2차원 벡터 a.T의 shape : (1, 5)


In [23]:
#print(np.dot(a,a))
#위 코드는 오류가 나기 때문에
print("a와 a.T를 곱하여 (5,1) (1,5)내적 곱의 짝을 맞춰준다 :\n",np.dot(a,a.T))

a와 a.T를 곱하여 (5,1) (1,5)내적 곱의 짝을 맞춰준다 :
 [[ 1.07982333  0.37710937  0.63611397  0.2026425  -1.69637199]
 [ 0.37710937  0.13169884  0.22215166  0.07076934 -0.59242818]
 [ 0.63611397  0.22215166  0.37472888  0.11937483 -0.99931711]
 [ 0.2026425   0.07076934  0.11937483  0.03802843 -0.31834564]
 [-1.69637199 -0.59242818 -0.99931711 -0.31834564  2.66495253]]
